### ISSUE TITLE
Unable to create new album 

### ISSUE THREAD

**Issue by ubaidsayyed54** [aws-samples/lambda-refarch-imagerecognition#12]
![image refarch](https://user-images.githubusercontent.com/20872638/34978489-67fa46e0-fac4-11e7-9ec1-459c96357a62.JPG)

Whenever I try to create a new album it throws an error.

**Comment by angelarw** [comment]
Hi, apologize for the delay in response. 
To help you trouble shoot, if you are using Chrome, can you open developer tools and let me know what error message you see in the **console** tab? https://developers.google.com/web/tools/chrome-devtools/

**Comment by angelarw** [comment]
Given long timeframe since the original post, i'll close this issue for now. feel free to reopen if you are still experiencing the error
