### ISSUE TITLE
Error with CloudFormation

### ISSUE THREAD

**Issue by rocky1011** [aws-samples/lambda-refarch-imagerecognition#15]
Hi,
during the creation with the cloudformation I see this error:

The  runtime parameter of nodejs4.3 is no longer supported for creating or  updating AWS Lambda functions. We recommend you use the new runtime  (nodejs8.10) while creating or updating functions. (Service:  AWSLambdaInternal; Status Code: 400; Error Code:  InvalidParameterValueException; Request ID:  d5fedcf4-215f-11e9-984c-1b75dc1aca1b)
![error](https://user-images.githubusercontent.com/47056327/51786786-a4b32f80-2169-11e9-9708-3285a8751f7e.png)

do you have any idea how to solve it?

thank you
![error](https://user-images.githubusercontent.com/47056327/51786791-bc8ab380-2169-11e9-88b3-4a97e57362fa.png)

**Comment by angelarw** [comment]
Hi rocky1011,

Thanks for reporting. I will update the cloudformation template to use the latest nodejs version

**Comment by angelarw** [comment]
issue fixed.
