### ISSUE TITLE
Role policy need to be updated in Step3

### ISSUE THREAD

**Issue by derFaizio** [aws-samples/lambda-refarch-imagerecognition#19]
Following the documentation, if you have created a new IAM role for Step Functions, this only includes permission to invoke the ExtractMetadata Lambda function. 

When adding two new Lambda function invocations in the parallel path in Step3, the execution would fail with an 403 Access denied error. 

```
{
  "error": "Lambda.AWSLambdaException",
  "cause": "User: arn:aws:sts::012345678910:assumed-role/StepFunctionExecutionRoleForImageProcessing/ahHmwmWNKuHXeWtEOlzRZuOFiwpoCyKH is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:eu-west-1:012345678910:function:sfn-workshop-setup-DetectLabel (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: 7b05b2e7-a480-48e1-aa04-a77181f3e179)"
}
```

To fix this error, add the arn of the newly added functions to the Resource in the IAM Role Permissions.

**Comment by angelarw** [comment]
added a deprecation notice for the workshop subsection - the workshop is no longer actively maintained, even though the main repo still is. 
for an up-to-date serverless image processing workshop, check out  https://image-processing.serverlessworkshops.io/
