### ISSUE TITLE
AlbumID  - expression not defined

### ISSUE THREAD

**Issue by rijhsinghani** [aws-samples/lambda-refarch-imagerecognition#20]
Hi  - running into this error when triggering via a direct upload to s3 bucket, which prevents the metadata from being written to dynamoDB. Any suggestions?

"errorMessage": "Invalid UpdateExpression: An expression attribute value used in expression is not defined; attribute value: :albumID",

**Comment by angelarw** [comment]
i pushed a new version of the app that should have resolved this issue
