### ISSUE TITLE
cloudformation templates still ref node8

### ISSUE THREAD

**Issue by magic7s** [aws-samples/lambda-refarch-imagerecognition#25]
PR https://github.com/aws-samples/lambda-refarch-imagerecognition/pull/21 changed the runtime of lambda functions to node10 but did not update cloudformation template's s3 source files. 

Execution of CFT per README.md at s3://media-sharing-refarch/cloudformation/image-processing-v3-node8.output.yaml builds node8 (actually fails on lambda function creation)

**Comment by angelarw** [comment]
thanks for calling it out. i will work on this asap

**Comment by gypsydang** [comment]
I encounter this issue too. By replacing all the "nodejs8.10" by "nodejs12.x", the problem solved.

**Comment by angelarw** [comment]
i updated the template in the latest commit to master. let me know if it works for you now

**Comment by gypsydang** [comment]
yes, it works. Thank you.

Angela Wang <notifications@github.com> 于2020年3月17日周二 上午9:49写道：
